set windows-shell := ["pwsh.exe", "-NoLogo", "-Command"]

default:
    @just --list

all:
  just std
  just serde
  just tonic
  just gpui

std:
  cargo run -p crate-paths-cli --features specific -- -o ./std-crate-paths/src/lib.rs rustup -c std

serde:
  cargo run -p crate-paths-cli --features specific -- -o ./serde-crate-paths/src/lib.rs local -c serde

tonic:
  cargo run -p crate-paths-cli --features specific -- -o ./tonic-crate-paths/src/lib.rs docsrs -c tonic

gpui:
  cargo run -p crate-paths-cli --features specific -- -o ./gpui-crate-paths/src/lib.rs local -c gpui
  cargo run -p crate-paths-cli --features specific -- -o ./gpui-component-crate-paths/src/lib.rs local -c gpui-component
